version: "3"
services:
  web:
    image: 069194799098.dkr.ecr.eu-central-1.amazonaws.com/rspec-test1:latest
    stop_grace_period: 30s
    ports:
    - 3000:3000
    restart: "no"
    tty: true
    stdin_open: true
    working_dir: "/codebase"
    command: bash -c "
             rails db:migrate &&
             rm -f tmp/pids/server.pid &&
             rails s -b 0.0.0.0"
    deploy:
      replicas: 3
      update_config:
        delay: 10s
        parallelism: 1
        failure_action: rollback
    # volumes:
    #       - syrincs1:/shared_data
    # depends_on:
    #   - db
    #   - redis
  # redis:
  #   image: redis
  # db:
  #   image: postgres             

# volumes:
#   syrincs1:
#     driver: "cloudstor:aws"
#     driver_opts:
#       backing: relocatable
#       size: 2
#       ebstype: gp2
